#include "stm32f1xx.h"
#include "rcc.h"

void HSE_8MHZ(void)
{
	RCC->CR |=RCC_CR_HSEON;
	
	while((RCC->CR & RCC_CR_HSERDY) == 0);
	
	RCC->CFGR &= ~(RCC_CFGR_SW);
	RCC->CFGR |=RCC_CFGR_SW_HSE;
		
	while((RCC->CFGR & RCC_CFGR_SWS) != RCC_CFGR_SWS_HSE);

}

void HSE_PLL_SYS_CLK_MAX(void)
{
	RCC->CR |= RCC_CR_HSEON;
	while ((RCC->CR & RCC_CR_HSERDY) == 0)
		;

	FLASH->ACR |=FLASH_ACR_LATENCY_2 |FLASH_ACR_PRFTBE;


	RCC->CFGR |= RCC_CFGR_PLLSRC;
	RCC->CFGR |= RCC_CFGR_PLLMULL9;
	RCC->CFGR |= RCC_CFGR_PPRE1_DIV2;
	RCC->CFGR |= RCC_CFGR_ADCPRE_DIV6;

	RCC->CR |= RCC_CR_PLLON;

	//RCC->CFGR &= ~RCC_CFGR_SW;
	RCC->CFGR |= RCC_CFGR_SW_PLL;

	while ((RCC->CR & RCC_CR_PLLRDY) == 0)
		;
}

